name: what_todo
description: A simple todo app in flutter.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  flutter:
    sdk: flutter
  google_fonts: 
  http: ^0.13.3
  path: null
  sqflite: null

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
